// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDohACYKqZiyuT5WOr3_RRLCA1u0DtZ2pc',
    appId: '1:151465332652:web:cc535f6ebfc254fc2eb409',
    messagingSenderId: '151465332652',
    projectId: 'projectpulse-ecfb0',
    authDomain: 'projectpulse-ecfb0.firebaseapp.com',
    storageBucket: 'projectpulse-ecfb0.appspot.com',
    measurementId: 'G-R5TF5HL961',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBMXNCgVx3HybQ5bWlgyu1O_1rpXsDgp-o',
    appId: '1:151465332652:ios:516baeb04dfb04bd2eb409',
    messagingSenderId: '151465332652',
    projectId: 'projectpulse-ecfb0',
    storageBucket: 'projectpulse-ecfb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0vpOGPMw_Zyd9iyjrYYXxIrs6BXVaU6I',
    appId: '1:151465332652:android:7a2a030ad88a1ce22eb409',
    messagingSenderId: '151465332652',
    projectId: 'projectpulse-ecfb0',
    storageBucket: 'projectpulse-ecfb0.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMXNCgVx3HybQ5bWlgyu1O_1rpXsDgp-o',
    appId: '1:151465332652:ios:516baeb04dfb04bd2eb409',
    messagingSenderId: '151465332652',
    projectId: 'projectpulse-ecfb0',
    storageBucket: 'projectpulse-ecfb0.appspot.com',
    iosClientId:
        '151465332652-rjign7jtl627os7rllkm8tuerrodd8ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPulse',
  );
}
